### ISSUE TITLE
Починить стейдж. Проблемы с запуском контейнера

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#507]
# Где был обнаружен баг ?

Как оказалось, стейдж не стартует. Необходимо залезть на сервер и узнать в чем причина. Пофиксить

# Скриншоты

![2024-07-25_19-16](https://github.com/user-attachments/assets/6cb09b20-acd2-4515-81a2-1d4913d58bac)

# Предложения и предположения как исправить

Проверить по миграциям. Возможно надо очистить вольюмы

**Comment by KonstantinRaikhert** [comment]
@trippiez У тебя же у же есть доступ к машине. Посмотри пожалуйста

**Comment by KonstantinRaikhert** [comment]
@ramil-khan Возьмешь таску? Доступ дам, как пришлешь свой public key

**Comment by ramil-khan** [comment]
Контейнер `adaptive_hockey_federation` на стейдже постоянно рестартует:
```
CREATED       STATUS
4 hours ago   Restarting (3) 24 seconds ago
```

В логах — сообщения о том, что некоторые переменные окружения не установлены.
@KonstantinRaikhert Можно ли проверить — созданы ли секреты для Actions для переменных, упомянутых в логах ниже? Я не смог проверить — у меня нет доступа к настройкам репозитория, насколько я могу видеть.

```
WARN[0000] The "DB_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IMAGE_COMPOSE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ST" variable is not set. Defaulting to a blank string. 
1 error(s) decoding:

* error decoding 'ports': No port specified: 5432:<empty>
```

**Comment by KonstantinRaikhert** [comment]
> Контейнер `adaptive_hockey_federation` на стейдже постоянно рестартует:
> 
> ```
> CREATED       STATUS
> 4 hours ago   Restarting (3) 24 seconds ago
> ```
> 
> В логах — сообщения о том, что некоторые переменные окружения не установлены. @KonstantinRaikhert Можно ли проверить — созданы ли секреты для Actions для переменных, упомянутых в логах ниже? Я не смог проверить — у меня нет доступа к настройкам репозитория, насколько я могу видеть.
> 
> ```
> WARN[0000] The "DB_PORT" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "IMAGE_COMPOSE" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "PORT" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "HOST" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "ST" variable is not set. Defaulting to a blank string. 
> 1 error(s) decoding:
> 
> * error decoding 'ports': No port specified: 5432:<empty>
> ```

Всё ясно! Выдал тебе админ права, посмотри пожалуйста в репозитории в environments

**Comment by ramil-khan** [comment]
Дополнительный анализ показал, что контейнер не стартует из-за проблемы с зависимостями:
`ModuleNotFoundError: No module named 'requests'`
`ImportError: libGL.so.1: cannot open shared object file: No such file or directory`
После исправления зависимостей и пересборки имиджа контейнер запустился локально. Для дальнейшей верификации предлагаю задеплоить стейдж с фиксом.

Кроме того, в секретах Actions не задана переменная окружения `ST` (остальные переменные заданы и передаются в .env файл на стейдже).
Ворнинги в логах docker compose возникают из-за использования на стейдже переменных окружения, которые не были установлены ([docker-compose.stage.yaml](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/blob/dev/infra/stage/docker-compose.stage.yaml)).

**Comment by ramil-khan** [comment]
@KonstantinRaikhert Лог контейнера на стейдже, ошибка импорта `requests`:
```
[2024-08-09 17:59:26 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2024-08-09 17:59:26 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2024-08-09 17:59:26 +0000] [1] [INFO] Using worker: sync
[2024-08-09 17:59:26 +0000] [6] [INFO] Booting worker with pid: 6
[2024-08-09 20:59:27 +0300] [6] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/adaptive_hockey_federation/core/wsgi.py", line 10, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/adaptive_hockey_federation/games/apps.py", line 13, in ready
    import games.signals  # noqa
    ^^^^^^^^^^^^^^^^^^^^
  File "/app/adaptive_hockey_federation/games/signals.py", line 9, in <module>
    from video_api.tasks import get_player_video_frames
  File "/app/adaptive_hockey_federation/video_api/tasks.py", line 11, in <module>
    from service.a_hockey_requests import send_request_to_process_video
  File "/app/adaptive_hockey_federation/service/a_hockey_requests.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[2024-08-09 20:59:27 +0300] [6] [INFO] Worker exiting (pid: 6)
[2024-08-09 17:59:27 +0000] [1] [ERROR] Worker (pid:6) exited with code 3
[2024-08-09 17:59:27 +0000] [1] [ERROR] Shutting down: Master
[2024-08-09 17:59:27 +0000] [1] [ERROR] Reason: Worker failed to boot.
```

После добавления `requests` возникает другая ошибка:
```
adaptive_hockey_federation % docker run ahf3
[2024-08-09 17:56:41 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2024-08-09 17:56:41 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2024-08-09 17:56:41 +0000] [1] [INFO] Using worker: sync
[2024-08-09 17:56:41 +0000] [7] [INFO] Booting worker with pid: 7
[2024-08-09 20:56:42 +0300] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/adaptive_hockey_federation/core/wsgi.py", line 10, in <module>
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/app/adaptive_hockey_federation/games/apps.py", line 13, in ready
    import games.signals  # noqa
    ^^^^^^^^^^^^^^^^^^^^
  File "/app/adaptive_hockey_federation/games/signals.py", line 9, in <module>
    from video_api.tasks import get_player_video_frames
  File "/app/adaptive_hockey_federation/video_api/tasks.py", line 12, in <module>
    from service.video_processing import slicing_video_with_player_frames
  File "/app/adaptive_hockey_federation/service/video_processing.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[2024-08-09 20:56:42 +0300] [7] [INFO] Worker exiting (pid: 7)
[2024-08-09 17:56:42 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
[2024-08-09 17:56:42 +0000] [1] [ERROR] Shutting down: Master
[2024-08-09 17:56:42 +0000] [1] [ERROR] Reason: Worker failed to boot.
```

Если установить в образе контейнера пакет `libgl1-mesa-glx`, то вторая ошибка не возникает.
